[package]
name = "geoiprs"
version = "0.1.0"
authors = ["Ryoh Kawai <kawairyoh@gmail.com>"]
edition = "2018"

[dependencies]
quicli = "0.4.0"
structopt = "0.2.14"
maxminddb = "0.12.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
